const MODERATOR_SCRIPTS = {
  lone_wolf: "Sói Đơn Độc thức dậy. Hãy quan sát và thực hiện quyền của bạn theo luật bàn chơi. Sói Đơn Độc đi ngủ.",
  halfblood: "Bán Sói thức dậy để Quan Trò xác nhận vai và trạng thái ban đầu. Bán Sói đi ngủ.",
  mayor: "Thị Trưởng thức dậy để Quan Trò xác nhận quyền biểu quyết. Thị Trưởng đi ngủ.",
  tough_guy: "Người Cứng Cỏi thức dậy để Quan Trò xác nhận hiệu ứng sống sót. Người Cứng Cỏi đi ngủ.",
  rusty_knight: "Kỵ Sĩ Rỉ Sét thức dậy để Quan Trò xác nhận hiệu ứng phản công. Kỵ Sĩ Rỉ Sét đi ngủ.",
  diseased: "Người Bệnh thức dậy để Quan Trò xác nhận hiệu ứng khi bị Sói tấn công. Người Bệnh đi ngủ.",
  hoodlum: "Kẻ Du Côn thức dậy. Hãy chọn các mục tiêu theo luật bàn chơi và chỉ cho Quan Trò. Kẻ Du Côn đi ngủ.",
  cupid: "Thần Tình Yêu thức dậy. Hãy chọn hai người trở thành đôi tình nhân và chỉ cho Quan Trò. Thần Tình Yêu đi ngủ.",
  guard: "Bảo Vệ thức dậy. Đêm nay bạn muốn bảo vệ ai? Hãy chỉ cho Quan Trò. Bảo Vệ đi ngủ.",
  priest: "Linh Mục thức dậy. Hãy chọn mục tiêu và thực hiện năng lực theo luật bàn chơi. Linh Mục đi ngủ.",
  werewolf: "Ma Sói thức dậy. Hãy nhận biết đồng đội và thống nhất một người bị tấn công đêm nay. Ma Sói chỉ mục tiêu cho Quan Trò rồi đi ngủ.",
  fruit_wolf: "Sói Ăn Chay thức dậy cùng phe Sói để nhận biết đồng đội và thực hiện luật riêng của vai. Sói Ăn Chay đi ngủ.",
  wolf_cub: "Sói Con thức dậy cùng phe Sói để nhận biết đồng đội. Nếu hiệu ứng Sói Con đang được kích hoạt, Quan Trò áp dụng luật bàn chơi. Sói Con đi ngủ.",
  minion: "Kẻ Hầu Sói thức dậy. Ma Sói giơ tay để Kẻ Hầu Sói nhận biết đồng minh. Kẻ Hầu Sói đi ngủ.",
  alpha_wolf: "Sói Đầu Đàn thức dậy cùng phe Sói. Hãy thống nhất mục tiêu và thực hiện năng lực đặc biệt nếu còn hiệu lực. Sói Đầu Đàn đi ngủ.",
  fang_face: "Sói Nanh Độc thức dậy cùng phe Sói để nhận biết đồng đội và xác nhận hiệu ứng riêng. Sói Nanh Độc đi ngủ.",
  vampire: "Ma Cà Rồng thức dậy. Hãy nhận biết đồng đội và thống nhất mục tiêu đêm nay. Ma Cà Rồng chỉ mục tiêu cho Quan Trò rồi đi ngủ.",
  witch: "Phù Thủy thức dậy. Đêm nay, {victims} sẽ chết. Bạn có muốn dùng bình thuốc cứu không? Bạn có muốn dùng bình độc để chọn một người khác không? Phù Thủy đi ngủ.",
  seer: "Tiên Tri thức dậy. Đêm nay bạn muốn soi ai? Hãy chỉ một người; Quan Trò sẽ cho biết người đó có phải Ma Sói hay không. Tiên Tri đi ngủ.",
  aura_seer: "Tiên Tri Hào Quang thức dậy. Hãy chọn một người để xem hào quang theo luật bàn chơi. Tiên Tri Hào Quang đi ngủ.",
  mystic_seeker: "Nhà Thấu Thị thức dậy. Hãy chọn mục tiêu cho năng lực soi nâng cao và chờ tín hiệu của Quan Trò. Nhà Thấu Thị đi ngủ.",
  apprentice_seer: "Học Việc Tiên Tri thức dậy nếu năng lực đã được kích hoạt. Hãy chọn một người để soi. Học Việc Tiên Tri đi ngủ.",
  sorceress: "Phù Thủy Sói thức dậy. Hãy chọn một người để tìm kiếm vai trò theo luật bàn chơi. Phù Thủy Sói đi ngủ.",
  hunter: "Khi Thợ Săn bị loại, Quan Trò đọc: Thợ Săn đã bị loại và được chọn một người cùng rời bàn chơi.",
  huntress: "Nữ Thợ Săn thức dậy. Nếu muốn dùng năng lực, hãy chọn một mục tiêu và chỉ cho Quan Trò. Nữ Thợ Săn đi ngủ.",
  investigator: "Điều Tra Viên thức dậy. Hãy chọn một người để điều tra và chờ tín hiệu của Quan Trò. Điều Tra Viên đi ngủ.",
  spellcaster: "Pháp Sư thức dậy. Hãy chọn mục tiêu cho phép thuật đêm nay theo luật bàn chơi. Pháp Sư đi ngủ.",
  cursed: "Kẻ Bị Nguyền thức dậy để Quan Trò xác nhận trạng thái ban đầu. Nếu đã đổi phe, hãy làm theo hiệu ứng của bàn chơi. Kẻ Bị Nguyền đi ngủ.",
  old_hag: "Bà Phù Thủy Già thức dậy. Hãy chọn một người chịu ảnh hưởng trong ngày mai. Bà Phù Thủy Già đi ngủ.",
  mentalist: "Nhà Ngoại Cảm thức dậy. Hãy chọn mục tiêu để nhận thông tin theo luật bàn chơi. Nhà Ngoại Cảm đi ngủ.",
  gambler: "Kẻ Đánh Cược thức dậy. Hãy chọn hành động cho đêm nay và chỉ cho Quan Trò. Kẻ Đánh Cược đi ngủ.",
  cult_leader: "Thủ Lĩnh Giáo Phái thức dậy. Hãy chọn một người theo luật Giáo Phái và chỉ cho Quan Trò. Thủ Lĩnh Giáo Phái đi ngủ.",
  prince: "Khi Hoàng Tử bị biểu quyết loại, Quan Trò kiểm tra hiệu ứng sống sót của vai trước khi ghi nhận tử vong.",
  tanner: "Khi Kẻ Chán Đời bị biểu quyết loại, Quan Trò kiểm tra ngay điều kiện thắng riêng của vai.",
  villager: "Dân Làng không thức dậy ban đêm. Ban ngày, mọi người thảo luận và biểu quyết người bị nghi là Ma Sói.",
};

const BASE_ROLE_CATALOG = [
  { id: "lone_wolf", name: "Sói Đơn Độc", team: "werewolf", value: -4, phase: "Đêm đầu", nightOrder: 3, wakesAtNight: "night_one", ability: "Biết đồng minh hoặc hành động theo luật Quan Trò.", max: 1 },
  { id: "halfblood", name: "Bán Sói", team: "village", value: -1, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Vai trò đặc biệt do Quan Trò điều hành.", max: 1 },
  { id: "mayor", name: "Thị Trưởng", team: "village", value: 2, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Có ảnh hưởng trong phần biểu quyết theo luật bàn chơi.", max: 1 },
  { id: "tough_guy", name: "Người Cứng Cỏi", team: "village", value: 3, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Có khả năng sống sót sau một cuộc tấn công theo luật bàn chơi.", max: 1 },
  { id: "rusty_knight", name: "Kỵ Sĩ Rỉ Sét", team: "village", value: 5, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Mang hiệu ứng phản công theo luật bàn chơi.", max: 1 },
  { id: "diseased", name: "Người Bệnh", team: "village", value: 3, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Tạo hiệu ứng bất lợi cho Ma Sói nếu bị hại.", max: 1 },
  { id: "hoodlum", name: "Kẻ Du Côn", team: "other", value: 0, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", ability: "Theo mục tiêu riêng do Quan Trò công bố.", max: 1 },
  { id: "cupid", name: "Thần Tình Yêu", team: "village", value: 3, phase: "Đêm đầu", nightOrder: 1, wakesAtNight: "night_one", recommended: true, ability: "Chọn hai người yêu nhau trong đêm đầu.", max: 1 },
  { id: "guard", name: "Bảo Vệ", team: "village", value: 4, phase: "Mỗi đêm", nightOrder: 2, wakesAtNight: "every_night", recommended: true, ability: "Chọn một người để bảo vệ trong đêm.", max: 1 },
  { id: "priest", name: "Linh Mục", team: "village", value: 3, phase: "Mỗi đêm", nightOrder: 2, wakesAtNight: "every_night", ability: "Dùng năng lực theo luật bàn chơi.", max: 1 },
  { id: "werewolf", name: "Ma Sói", team: "werewolf", value: -6, phase: "Mỗi đêm", nightOrder: 3, wakesAtNight: "every_night", recommended: true, ability: "Cùng phe Sói chọn mục tiêu trong đêm.", max: 10 },
  { id: "fruit_wolf", name: "Sói Ăn Chay", team: "werewolf", value: -3, phase: "Đêm đầu", nightOrder: 3, wakesAtNight: "night_one", ability: "Vai trò Sói biến thể theo luật bàn chơi.", max: 1 },
  { id: "wolf_cub", name: "Sói Con", team: "werewolf", value: -8, phase: "Đêm đầu", nightOrder: 3, wakesAtNight: "night_one", ability: "Kích hoạt hiệu ứng khi bị loại theo luật bàn chơi.", max: 1 },
  { id: "minion", name: "Kẻ Hầu Sói", team: "werewolf", value: -6, phase: "Đêm đầu", nightOrder: 3, wakesAtNight: "night_one", ability: "Biết phe Sói và hỗ trợ phe Sói.", max: 1 },
  { id: "alpha_wolf", name: "Sói Đầu Đàn", team: "werewolf", value: -9, phase: "Mỗi đêm", nightOrder: 3, wakesAtNight: "every_night", ability: "Vai trò Sói có năng lực mạnh hơn theo luật bàn chơi.", max: 1 },
  { id: "fang_face", name: "Sói Nanh Độc", team: "werewolf", value: -5, phase: "Đêm đầu", nightOrder: 3, wakesAtNight: "night_one", ability: "Vai trò Sói biến thể theo luật bàn chơi.", max: 1 },
  { id: "vampire", name: "Ma Cà Rồng", team: "vampire", value: -7, phase: "Mỗi đêm", nightOrder: 3, wakesAtNight: "every_night", ability: "Phe Ma Cà Rồng hành động trong đêm.", max: 6 },
  { id: "witch", name: "Phù Thủy", team: "village", value: 5, phase: "Mỗi đêm", nightOrder: 4, wakesAtNight: "every_night", recommended: true, ability: "Có thuốc cứu và thuốc độc theo luật bàn chơi.", max: 1 },
  { id: "seer", name: "Tiên Tri", team: "village", value: 7, phase: "Mỗi đêm", nightOrder: 4, wakesAtNight: "every_night", recommended: true, ability: "Soi một người chơi trong đêm.", max: 1 },
  { id: "aura_seer", name: "Tiên Tri Hào Quang", team: "village", value: 3, phase: "Mỗi đêm", nightOrder: 4, wakesAtNight: "every_night", ability: "Soi hào quang theo luật bàn chơi.", max: 1 },
  { id: "mystic_seeker", name: "Nhà Thấu Thị", team: "village", value: 9, phase: "Mỗi đêm", nightOrder: 4, wakesAtNight: "every_night", ability: "Dùng năng lực soi nâng cao theo luật bàn chơi.", max: 1 },
  { id: "apprentice_seer", name: "Học Việc Tiên Tri", team: "village", value: 4, phase: "Mỗi đêm", nightOrder: 4, wakesAtNight: "every_night", ability: "Có thể kế nhiệm hoặc soi theo luật bàn chơi.", max: 1 },
  { id: "sorceress", name: "Phù Thủy Sói", team: "werewolf", value: -3, phase: "Đêm đầu", nightOrder: 4, wakesAtNight: "night_one", ability: "Hỗ trợ phe Sói bằng năng lực riêng.", max: 1 },
  { id: "hunter", name: "Thợ Săn", team: "village", value: 3, phase: "Khi bị loại", nightOrder: 5, wakesAtNight: "never", recommended: true, ability: "Khi bị loại, có thể chọn một người cùng rời bàn chơi.", max: 1 },
  { id: "huntress", name: "Nữ Thợ Săn", team: "village", value: 3, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Dùng năng lực theo luật bàn chơi.", max: 1 },
  { id: "investigator", name: "Điều Tra Viên", team: "village", value: 4, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Điều tra một người chơi theo luật bàn chơi.", max: 1 },
  { id: "spellcaster", name: "Pháp Sư", team: "village", value: 1, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Dùng phép theo luật bàn chơi.", max: 1 },
  { id: "cursed", name: "Kẻ Bị Nguyền", team: "village", value: -2, phase: "Đêm đầu", nightOrder: 5, wakesAtNight: "night_one", recommended: true, ability: "Có thể đổi phe trong điều kiện do luật bàn chơi quy định.", max: 1 },
  { id: "old_hag", name: "Bà Phù Thủy Già", team: "village", value: 1, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Dùng năng lực gây ảnh hưởng theo luật bàn chơi.", max: 1 },
  { id: "mentalist", name: "Nhà Ngoại Cảm", team: "village", value: 4, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Nhận thông tin theo luật bàn chơi.", max: 1 },
  { id: "gambler", name: "Kẻ Đánh Cược", team: "village", value: 2, phase: "Từ đêm 2", nightOrder: 5, wakesAtNight: "from_night_two", ability: "Chọn hành động từ đêm thứ hai.", max: 1 },
  { id: "cult_leader", name: "Thủ Lĩnh Giáo Phái", team: "other", value: 1, phase: "Mỗi đêm", nightOrder: 5, wakesAtNight: "every_night", ability: "Theo mục tiêu phe riêng do Quan Trò điều hành.", max: 1 },
  { id: "prince", name: "Hoàng Tử", team: "village", value: 2, phase: "Không thức", nightOrder: 99, wakesAtNight: "never", ability: "Có hiệu ứng sống sót hoặc biểu quyết theo luật bàn chơi.", max: 1 },
  { id: "tanner", name: "Kẻ Chán Đời", team: "other", value: -2, phase: "Không thức", nightOrder: 99, wakesAtNight: "never", ability: "Thắng theo điều kiện riêng khi bị loại.", max: 1 },
  { id: "villager", name: "Dân Làng", team: "village", value: 1, phase: "Không thức", nightOrder: 99, wakesAtNight: "never", recommended: true, ability: "Dùng suy luận và biểu quyết để tìm phe đối nghịch.", max: 30 },
];

export const ROLE_CATALOG = BASE_ROLE_CATALOG.map((role) => ({
  ...role,
  moderatorScript: MODERATOR_SCRIPTS[role.id],
}));

export const ROLE_BY_ID = new Map(ROLE_CATALOG.map((role) => [role.id, role]));

export const BALANCE_MODES = {
  new_players: { id: "new_players", name: "Nhóm mới", target: 2, min: 1, max: 3, guidance: "Ưu tiên phe Dân để bàn chơi dễ làm quen." },
  balanced: { id: "balanced", name: "Cân bằng", target: 0, min: -3, max: 3, guidance: "Giữ tổng điểm gần bằng không." },
  experienced: { id: "experienced", name: "Nhóm quen", target: -2, min: -3, max: -1, guidance: "Cho phe Sói một lợi thế nhỏ." },
};
